---
title: "Kareem Hunt NLP and Sentiment"
author: "Julianna Alvord"
date: "12/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(monkeylearn)
library(magrittr)
```

```{r}
top100_HUNT <- top100_more %>%
  filter(lastname == "HUNT")

twitter <- top100_HUNT$fortwitter

twitter[2] <- "Kareem Hunt"

datalist = list()

for(handle in twitter) {
  result <- search_tweets(handle, n = 18000, include_rts = FALSE)
  result$Source <- handle
  
  words <- result %>% 
    select(status_id, text) %>% 
    unnest_tokens(word,text)
    
  my_stop_words <- stop_words %>% select(-lexicon) %>% 
  bind_rows(data.frame(word = c("https", "t.co", "rt", "amp","4yig9gzh5t","fyy2ceydhi","78","fakenews")))

  tweet_words <- words %>% anti_join(my_stop_words)
  
  bing_lex <- get_sentiments("nrc")

  fn_sentiment <- tweet_words %>% 
    left_join(bing_lex) 
  
  df <- fn_sentiment %>% filter(!is.na(sentiment)) %>% group_by(sentiment) %>% summarise(n=n())

  df_2 <- df %>%
  mutate(player = handle) %>%
    spread(key = sentiment, value = n)
  
  datalist[[handle]] <- df_2
  
  #creating names
  df_name <- substring(handle, 1)
  
  words_name <- paste(substring(handle, 1), "word", sep = "_")

  if(exists(df_name)) {
    assign(df_name, unique(rbind(get(df_name), result)))
  } else {
    assign(df_name, result)
    
    assign(words_name, df_2)
  }
  Sys.sleep(900)
}

sentiments_T1 = do.call(rbind, datalist)
```

#
```{r}

```

