---
title: "play by play"
author: "Julianna Alvord"
date: "12/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#analyzing mayfield vs barkley
```{r}
#bringing in pbp data
pbp_2018 <- read.csv("pbp-2018.csv")

#filtering for mayfield or barkley
pbp_2018_filtered <- pbp_2018 %>%
  mutate(barkley = ifelse(grepl("BARKLEY", Description, fixed = TRUE), 1, 0),
         mayfield = ifelse(grepl("MAYFIELD", Description, fixed = TRUE), 1, 0)) %>%
  filter(barkley == 1|mayfield == 1) %>%
  mutate(player = ifelse(barkley == 1, "barkley",
                         ifelse(mayfield == 1, "mayfield", "both")))


#how successful are they?
pbp_yards <- pbp_2018_filtered %>%
  group_by(player) %>%
  summarise(mean_yards = mean(Yards),
            median_yards = median(Yards),
            min_yards = min(Yards),
            max_yards = max(Yards))

#plotting distribution of yards
ggplot(pbp_2018_filtered, aes(Yards, fill = player)) + geom_density(alpha = 0.6)
#similar distributions
```