---
title: "SB Analysis"
author: "Julianna Alvord"
date: "2/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(data.table)
library(tidyr)
```

#loading in tweets and starters
```{r}
load("/Volumes/easystore/Thesis/superbowl_tweets.rda")

starters <- read.csv("/Users/juliannaalvord/Documents/nfl sentiment/sb_starters.csv", stringsAsFactors = FALSE)
```

#creating same list of 92 which was used to stream twitter
```{r}
name <- starters$players

#cleaning twitter column, selecting that column, then filtering out those without twitter handle
twitter_clean <- starters %>%
  mutate(twitter_clean = sub("'", "", twitter)) %>%
  select(twitter_clean) %>%
  filter(!twitter_clean == "")

#list of twitter handles
twitter <- twitter_clean$twitter_clean

#full name and twitter handle for streaming
full <- c(name, twitter)

#making list for str_extract_all
all_players <- paste(full, collapse='|')
```


#creating new column of players names
```{r}
#lowercasing player/handles for searching of text/quoted text
all_players_low = tolower(all_players)

#lower casing text and quoted text to be able to search without missing any players
rt_more <- rt %>%
  mutate(text_low = tolower(text),
         quoted_text_low = tolower(quoted_text),
         #pulling out the players from either text or quoted text
         name_text = str_extract_all(paste(text_low, quoted_text_low, sep = ","), pattern = all_players_low),
         #hour created, just for vizs
         hour = hour(created_at))
```

#joining based on list column
```{r}
#unnesting the name_text list column
rt_more2 <- rt_more %>%
  unnest(name_text)
```

#creating two 
```{r}
#lowering twitter handles and player names for join
starters2 <- starters %>%
  mutate(twitter_clean = sub("'", "", twitter),
         twitter_clean2 = tolower(twitter_clean),
         name_clean = tolower(players)) %>%
  select(-c(players, twitter, twitter_clean))

#filtering for tweets that mention a player by their @
tweets_names <- rt_more2 %>%
  filter(!grepl("@", name_text))

#filtering for tweets that mention a player by their full name
tweets_handles <- rt_more2 %>%
  filter(grepl("@", name_text))
```

#joining each of these two new dfs with starters data (including race)
```{r}
#tweets with names join
tweets_names2 <- tweets_names %>%
  left_join(starters2, by = c("name_text" = "name_clean"))

#tweets with handles join
tweets_handles2 <- tweets_handles %>%
  left_join(starters2, by = c("name_text" = "twitter_clean2"))

#row binding those two
tweets_final <- tweets_handles2 %>%
  bind_rows(tweets_names2) %>%
  #next code creates final name and twitter columns by filling in with name_text (what was joined on)
         #in tweets with names df, left join gets rid of "name_clean" col
  mutate(name_clean_final = ifelse(is.na(name_clean), name_text, name_clean),
         #in tweets with handles df, left join gets rid of "twitter_clean2" col
         twitter_clean_final = ifelse(is.na(twitter_clean2), name_text, twitter_clean2))
```

#further cleaning of 
```{r}
tweets_final <- tweets_final %>%
  #getting rid of incomplete names and twitter handles columns
  select(-c(name_clean, twitter_clean2)) %>%
  #making a col of full text (includes quoted text)
  mutate(full_text = paste(text_low, quoted_text_low, sep = ","))

#need to change one name 
tweets_final <- tweets_final %>%
  mutate(name_clean_final = ifelse(name_clean_final == "deatrich wise jr ", "deatrich wise jr.", name_clean_final))

#number for each player
player_n <- tweets_final %>%
  group_by(name_clean_final) %>%
  summarise(n = n(),
            race = max(Race)) %>%
  arrange(desc(n))

#now how many for each race group %>%
race_n <- player_n %>%
  group_by(race) %>%
  summarise(total = sum(n))
```

#adding in a rm function (get rid if necessary)
```{r}
rm(starters, new_data, rt_more, tweets_handles, tweets_handles2, tweets_names, tweets_names2, player_n, race_n)
```



#saving as a .rda file (again)
```{r}
save(rt, file = "/Users/juliannaalvord/Documents/nfl sentiment/unnest_tweets_final.rda")
```




#checking for duplicates