# Introduction {#intro}

In August of 2016, San Francisco 49ers quarterback Colin Kaepernick remained sitting by the team’s water coolers during the national anthem prior to a preseason game. Immediately, the gesture was widely questioned and criticized. Many fans found his actions to be disrespectful to the sacrifices made by military members. After the game, when asked by the NFL media why he refused to stand, Kaepernick responded by stating, “I am not going to stand up to show pride in a flag for a country that oppresses black people and people of color” [@hauser2016colin]. His decision, along with his eventual exit from the NFL, brought attention to racial injustice, peaceful protest, and their connection to sports. 

This event, while drawing criticism, also sparked conversations where the main negative emotions ranged from disappointment to hatred. The hateful language that flooded social media did not go unnoticed, and the quarterback’s image was tarnished beyond repair. Other black athletes, especially those who support Kaepernick, paid a similar price. This event created a connection between football and racially charged language. Although Kaepernick is no longer an active player in the NFL, his legacy, and the anger he fueled, is still evident. The analyses by the media focused mainly on the negative language aimed both at Kaepernick and other black players. However, most of these accounts were anecdotal, referencing a few, seemingly isolated events. The aftermath and lack of data-driven research on the topics addressed during this event are the motivation behind this work.

We believe that this negative language towards black players in the NFL is widespread and measurable. Given the relatively new techniques to analyze language and sentiment on a larger scale, research in this area is increasingly accessible to data scientists. Our goal is to quantify and model the accounts of racially disproportionate language on social media using these techniques in order to offer insight into the connection between racial inequality and sport. 

We conduct this research through two studies, both of which use data from Twitter. The first study focuses on Super Bowl LIII and provides an exploratory data analysis for the second, more balanced study. Here, tweets are gathered for a selected subset of quarterbacks and receivers, half of whom are white and half of whom are black. Our three-level multilevel model is fit to the data from this study. 


## Background

### Research Question

The main research question is as follows: Are sentiments on Twitter more negative towards black NFL players after controlling for game outcome, position, and quality of play?

### Racism in Sport

Although Colin Kaepernick’s actions resulted in widespread media attention, many previous studies have addressed issues of racism and racial inequality in football and sports. Most often, these topics are studied through the context of sports media. Early research began in 1977, where @rainville1977extent analysed covert forms of prejudice in television broadcasts of nationally televised football games. They found that white players were more likely to receive praise for “good” plays and less likely to receive negative feedback for “bad” plays when compared to their black counterparts. More recently, a 2014 study by @angelini2014competing analysed broadcasts from the 2012 London Summer Olympics to determine whether they revealed significant divergences in dialogues for athletes of different racial groups. During this time, white athletes were more likely to be mentioned and there were significant differences in the commentary for white, black, latino, asian, and middle eastern athletes.

The relationship between racism and sport does not simply lie within the media. However, racism in other areas of sports is not easy to determine. @hylton2016your argues that while it is important to contront frontstage racism, such as that observed in the media and in other, more explicit ways, researchers must be mindful of more subvert forms of racism within sport. Research on subvert forms of racism, such as that from fans, is few and far between. This may be due to lack of access to data. Many studies surrounding racist dialogue among fans rely on survey data. Research from @cleland2014fans drew from 2,500 responses from soccer fans to an anonymous survey, which aimed to examine the extent of racism within the sport. They found that half of respondents either witness or experience racism in some form. 

As seen from Kaepernick’s exile and from these previous studies, racism in the NFL, whether apparent or more subvert, is widespread. Although individuals questioning the protest cite military disrespect as their main concern, a study from @intravia2018racial found that on average, black respondents were more likely to support all types of anthem protests and believe players who choose to participate should not be punished, compared to white respondents. Those strong race effects remain even after controlling for several key correlates, suggesting that race is a key distinction between support and disapproval of these NFL anthem protests. 

Research on racism, both in sport and across other areas of society, is vital to the well being of people and athletes of color. Numerous studies investigate the relationships between racism and mental and physical health. @williams1999race found that stress due to stigma, along with individual and institutional discrimination can adversely affect health. Additionally, the study addressed how racism in the United States is, “responsible for the development of an organized system of policies and practices designed to create racial inequality.” Due to the powerful structure of this system, people of color are often forced to hide their experiences. This prejudicial system leads to negative outcomes for people of color, and this is no different in the context of sports. In a study by @burdsey2011joke, researchers found that all athletes, both racial minorities and racial majorities, tend to downplay the repercussions of racial microaggressions. Research using large-scale data focusing on racist and racially disproportionate language is necessary to bring attention to issues of racism in sport context and the subsequent extensive negative consequences.

### Sentiment Analysis

Research dating back to 2003 has illustrated the use of sentiment analysis to identify how sentiments are expressed and whether the expressions in a determined body of text indicate positive or negative opinions towards the subject [@nasukawa2003sentiment]. Sentiments are determined by processing the language and context of a text, usually by a human being. Sentiment analysis works in a similar way, but also allow for a more automated process of long or multiple texts. 
	
Two types of methods for sentiment analysis are often employed and discussed in the literature: machine-learning-based and lexical-based. Machine-learning approaches mainly rely on supervised classification methods, where labeled training data is required. This method can be easily specified to fit one’s data. However, there are issues of over-fitting to training data which leads to low applicability to testing data. Lexical-based methods use a predetermined list of words, known as a lexicon, where each word is matched to one or more sentiments. In order to achieve a similar level of specification as the machine-learning-based methods, these lexicons must be thorough and contextual to the project at hand [@gonccalves2013comparing].

Sentiment analysis is not a simple approach. The decision to use this method in a project requires an understanding of the levels of granularity that can be specified. Early research tended to analyze sentiments of entire documents, which can lower the accuracy of the overall polarity assessment [@zhang2009sentiment]. Instead, @meena2007sentence employ sentence-level analyses in order to focus on pieces, such as conjunctions, which can significantly change overall sentiment.

For projects such as this one, whose main purpose is to employ sentiment analysis to research a given topic instead of researching sentiment analysis itself, there will be issues of accuracy. The reason for this is that basic sentiment analyses focus on words individually to determine overall sentiment; conjunctions will not be addressed. Consider the phrase “not good”. Using the method introduced below, the phrase would be separated into “not” and “good”, where “good” would be categorized as positive and "not" would be ignored altogether. More details on how cases such as this are handled in this study can be found below. 

A simple process for conducting basic natural language processing and sentiment analyses in R is detailed by @textmining. Here, the authors use the tidy text format, which is described as one-token-per-row. Therefore, each word is a row which allows for an easy join to a lexicon that is specified to the project.


### Sentiment Analyses of Twitter and other Online Data

The goal of this project is to measure sentiments of football fans by obtaining social media data. Thus, it is necessary to determine which site would offer the proper information. We found that Twitter data is commonly used for large-scale sentiment analyses as it is a "massive social networking site" aimed at quick communication. Approximately 400 million tweets are published daily from Twitter's 140 million active users [@kumar2014twitter]. Due to its constant stream of data, many researchers utilize Twitter data for sentiment analysis projects. 

Our expectation that negative sentiments will be widespread throughout Twitter is backed by much research. @awan2014islamophobia examined 500 tweets to determine how Muslim individuals are being viewed and targeted by Twitter users. They found that “the Internet and social media sites such as Twitter have become a popular arena for online hate, partly due to their accessibility and the anonymity they offer for offenders who use it to intimidate, harass, and bully others.”

Anonymity plays a huge role in online hate and abuse found on Twitter. @christopherson2007positive discussed the positive and negative results of online anonymity. On the positive side, they offered privacy as an example. Online users can decide how much of themselves to share with others, which can have a positive effect on psychological well-being. On the negative side, the authors connect the theory of group polarization to online anonymity. They define group polarization as the “tendency for like-minded individuals to become more extreme in their thinking following a group discussion.” To connect back to the current project, our hypothesis is supported by our belief that many football fans are like-minded and Twitter offers an anonymous platform for anti-black sentiments to become more extreme. 

The anonymity of the internet allows for hate speech and anti-black sentiments to thrive for another reason. Racist comments can be made on social media sites more freely and without consequence compared with offline face-to-face interactions. Online anonymity provides individuals with a sense of identity disguise or social distance from others which in turn leads to the disclosure of racist ideologies with minimal oversight [@keum2018racism]. 

@cleland2014racism found specific evidence of racism online in a sports context. Their study examined 500 posts from an online message board to determine the level and nature of racist language among European Football fans. They found extensive racist and Islamaphobic examples throughout the platform, many of which took place during fan interaction. These online incidents followed two high-profile incidents of racism on the field in 2011 in the UK. Some black players responded by reporting racist messages to the proper authorities while others were forced to remain silent. This matches @king2004offside argument that black players often succeed *despite* racism. He describes that many black players are required to "play the white man" in order to be accepted.

Focusing on Twitter, @stephens2013geography tracked over 150,000 accounts of public racist tweets over the course of the year. This suggests that the trend of racist online language is certainly true on Twitter. Also, sports fan involvement has increased in the past few years with the introduction of game-specific hashtags that guide conversation [@weller2014twitter]. Expanded Twitter activity prompts fan interactions and further data of game reactions, making tweets the ideal text for this project.

### Multi-Level Modeling

This project uses data that is grouped at different levels, where the processes occurring at a higher level influence the processes of a lower level. The levels in this case include team, individual players, and time. Specifically, time points are nested within the player level and players are nested within teams. Data that is structured in a heirarchical way is often found within social science contexts, due especially to natural groupings that occur with humans. Longitudinal data, such as the data in this study, also creates heirarcical structure as multiple data points for one individual are present. In order to test the hypothesis and answer the research question for this project, multilevel models are necessary. If we chose to use simpler modeling techniques in this situation, serious theoretical and statistical issues would be present. Those methods are employed with the assumption that the data is independent. However, given that longitudinal (and otherwise heirarcical) data includes multiple observations for one individual, that assumption is violated.

Two fallacies that can occur when applying non-multilevel modeling techniques on leveled data are ecological fallacies and atomistic fallacies. The first occurs when patterns observed for groups are assumed to hold true for individuals when this is not necessarily true. The latter occurs when the opposite occurs, namely that patterns observed for individuals are assumed to hold true for groups [@luke2004multilevel]. 

## Our Contribution

### Our Results

On average, the percentage of negative words during a loss decreases by 7.22% for white players relative to black players, holding position and yards constant. During a win, there is almost no difference in sentiment between white and black players. This demonstrates the racial bias of football fans on Twitter.

### Reproducible Research

As statistical analyses of data become increasingly common and complex, reproducibility becomes increasingly necessary. In order for research to be reproducible, proper documentation of methodology is crucial. However, this is not practiced by many researchers, especially due to the lack of proper technology. One way to improve statistical reproducibility, a term used by @stodden2014scientific, is by utilizing RMarkdown, an open source markup language. This tool allows for better workflow, by combining a statistical package with a layout package [@baumer2014r].

Given both the importance of reproducibility and the social relevance of this project, we use R Markdown throughout a majority of the cleaning and analyzing processes. However, gathering the data for one aspect this project required the use of Python. For this process, we use Jupyter Notebook, an open-source web application.

This thesis is being written using the `thesisdown` package in `R` [@solomon2019thesisdown]. `Thesisdown` was inspired by the `bookdown` package and offers an R Markdown template for undergraduate theses [@bookdown].

All of the documents from this project, whether they be R Markdown documents or Jupyter Notebooks, have been committed to [GitHub](https://github.com/jalvord1/nfl_sentiment), a code hosting platform [@github]. Github allows for easy code sharing and collaboration between researchers, making it the ideal platform to aid with reproducibility. 