# Ethics {#ethics}

##Data Ethics Overview

The recent increases in data access offer a unique opportunity for companies and researchers to make insights that would otherwise be impossible. These insights could lead to better disease tracking, optimization of business practices, or streamlining the hiring process, to name a few examples. The benefits of using data in research across all disciplines are extensive and cannot be understated. However, ensuring that the data usage is ethical and fair is a vital step in the process. 

As helpful as data can be, it can be equally as damaging and dangerous if used without consideration of the ethical consequences. @mittelstadt2016ethics state that researchers using big data must have ethical foresight instead of ethical hindsight, as the consequences of unethical data use are substantial. Despite the importance of data ethics, many people do not focus on ethics or issues of bias. Often, these issues stem from a lack of contextual understanding of data and data science techniques [@taylor2016no]. Additionally, there is a lack of a universal code of conduct for data scientists. One that is currently available comes from @national2018data. Although data can be used by researchers in any domain, knowledge of ethical issues of statistics and data analysis is not widespread. We will begin by combining multiple sources to create a thorough ethics guide for this project, specifically relating to research involving web scraping. 

### Theory-Driven Web Scraping

@landers2016primer argue that when scraping data from the web, researchers must follow a hypothetico-deductive modeling approach. This means that data is scraped with a hypothesis in mind and is gathered in order to test the hypothesis or answer a research question. This directs researchers away from hypothesizing after the results are already known. When data is scraped without a specific research question and the study design is unbalanced, it may be more likely for issues of content or construct validity to occur. These may go undetected and demonstrate results that do not accurately represent the phenomenon. The concept of creating a hypothesis after data is collected and analyzed is known as *post-hoc hypothesizing*. It is important to differentiate between presenting post-hoc hypotheses as a priori (PPHA) and presenting post-hoc hypotheses as those which require future empirical verification [@leung2011presenting]. The latter represents an acceptable process of research, whereas the former is considered unethical in most research domains.

@leung2011presenting specifies three types of widespread PPHA. In the first case, researchers create hypotheses directly from their results in order for their study to be theoretically compelling. In the second case, researchers will simply drop hypotheses that are dis-confirmed and fail to introduce them at all. In the third and final case, hypotheses may be added that appear to match the results but are presented as a priori. These methods lack the transparency necessary for ethical research practices. This type of post-hoc hypothesizing fails to account for previously studied relevant theoretical concepts, an important aspect of the research process. These issues can be magnified when using data scraped from the web, as larger sample sizes could lead to more statistically significant results. These studies may be more likely to be accepted for publication and therefore, ethically questionable research may direct future work on the topic. 

Additionally, investigators must recognize that results using scraped data cannot be generalized to the entire population, even if the sample appears widespread. The reason for this, specified by @wallace2015psychology, is that Internet users are inherently different than those who are not on the Internet. If the goal is to generalize toward other Internet users, that is acceptable in certain cases. However, it is unethical to assume results can be generalized any further. 

### Identifiability

Another important ethical issue of web scraping that must be considered is identifiability. Data from online sources often contain identifying information, even if it does not initially appear so. Data that can be used to distinguish or trace identities either alone or in combination with other information that is linkable to an individual is known as personally identifiable information (PII)  [@krishnamurthy2009leakage]. Given the huge increase in social network use, scandals involving data from these sources have been all over the news. Facebook, in particular, has come under scrutiny for their lack of data privacy and transparency. In 2008, Facebook announced that an attack on their servers resulted in the exposure of the personal data of over 50 million users [@facebookbreach]. While alarming, PII can be leaked without security breaches. The ability for researchers to use APIs or other computer science techniques to scrape data from these sites has also resulted in an unethical distribution of PII. As an example, researchers Emil Kirkegaard and Julius Daugbjerg Bjerrekær scraped data from OkCupid, and then released the data set for other researchers to use. However, the data included identifiable information of users, including their sexual preferences, politics, and feelings about homosexuality, among others [@resnick2016researchers]. 

When Kirkegaard was questioned about this ethical breach, he argued that the data were already public and therefore their scraped data was simply making the information accessible for research [@resnick2016researchers]. This example brings light to the delicate balance of data accessibility and privacy. While reproducibility of research is important, avoiding ethical issues that arise with PII must be given equal attention. Often, determining that line is left up to the discretion of the researcher. Therefore, it is necessary for researchers to be constantly aware of the ethical consequences of gathering and sharing data. In the context of the OkCupid example and the argument from the primary investigator, while the data was technically public, the users did not consent for their data to be used and shared for research outside of the OkCupid website. 

Sharing PII can result in consequences that extend beyond simply a lack of consent. @floridi2016data warn that it can lead to serious problems that range from group discrimination (racism, sexism, ageism, etc.) to group-targeted forms of violence. When evaluating the multiple ethical concerns of big data research, one solution is to follow the two moral duties introduced by @floridi2014open: to foster human rights and improve human welfare. If that is the ultimate goal of the research, ethical concerns will be minimized.

### Connection to this Research

Throughout the process of this research, we address and attempt to avoid any and all ethical concerns. First, we follow the theory-driven web scraping approach in the second study when connecting to the Twitter API to gather tweets. Our study is designed purposefully to answer our research question and test our hypothesis. We do not hypothesize post-hoc a priori nor do we generalize our results to populations past football fans who use Twitter. In the first study, we did not necessarily follow a theory-driven web scraping approach but we also did not fit models or perform any statistical inference tests.

While gathering tweets through the Twitter streaming and full-archive APIs, we only select certain meta-data to be included in our final data sets. These do not include usernames, IDs, or other personally identifiable information. Our goal is to analyze sentiments from the words of the tweets and this process is not at all related to the specific users who produced said tweets. As the code we use to gather the tweets is uploaded to GitHub, another researcher could alter the functions we wrote to include identifying variables into the data set. That being said, the only identifiable data that could be gathered is a person's handle. This cannot be used to link to other demographic data.
