# Final Remarks

This project began after witnessing qualitative evidence of negative language aimed at black players in the NFL. Especially following Colin Kaepernick kneeling to bring awareness to racial injustices in the United States, the NFL became a controversial topic. The resulting fallout of these events, in conjunction with previous research connecting racism and racial inequality in sports contexts, lead us to our research question and hypotheses. Given the racially charged climate within the NFL and football fans during the past few years, we believed that this racially disproportionate language could be observed on a larger scale and subsequently modeled. 

With the use of multilevel modeling techniques, we are able to account for the hierarchical nature of our data and produce more accurate coefficient estimates. The most important result of our main study is that the black players in our study had higher percentages of negative words on average, accounting for position, game outcome, and individual performance. This disparity is even more prominent during a game that was lost, suggesting that blame may be falling on black players instead of across all players regardless of race.

We urge researchers to continue to use Twitter and other social media data to investigate racism and racial inequality within sports contexts. Data driven insights can be particularly compelling, especially as research and policy begins to rely even more heavily on big data during decision-making processes.  

